### ISSUE TITLE
SetCookie Header didn't specify a "SameSite" attribute -  Set Authentication Cookie Option

### ISSUE THREAD

**Issue by jimmysafe** [AxeWP/wp-graphql-headless-login#104]
### Description

Hi,

I have created a simple React App (running on http://localhost:5173) that fetches data through WPGraphql.
I have installed [wp-graphql-headless-login](https://github.com/AxeWP/wp-graphql-headless-login) in order to get Social login features (Google and Facebook).

I am in the process of configuring the Google auth and i would like the wp-headless-login plugin to set the wp authentication cookie automatically on login success.

I am now able to login and create the logged in user automatically in wordpress. 
The problem i am facing is that the wp auth cookie does not get set because it is lacking of the `SameSite` attribute. 
I can see that the request tries to set the wp auth cookie but it does not get set.

Here is a screenshot:

![Screenshot 2023-12-21 at 18 28 21](https://github.com/AxeWP/wp-graphql-headless-login/assets/12184812/6cb3950b-1a69-41e9-b03d-ca0d9d164b59)

There is no way for me within the plugin to change the `SameSite` attribute to `none` ?

here is my plugin configuration

![Screenshot 2023-12-21 at 18 30 00](https://github.com/AxeWP/wp-graphql-headless-login/assets/12184812/732eff24-b759-45ed-9ea8-eb5a50a667a6).

### Steps to reproduce

1. Install the plugin
2. add a Google provider along with CLIENT ID and CLIENT SECRET.
3. In the plugin **Login Settings** TURN ON all settings.
4. In the plugin **Access Control Settings** TURN ON Block unauthorized domains and Add ACAC.
5. Set the locally running react frontend url in the authorized domains.

### Plugin Version

0.1.4

### WordPress Version

6.4.2

### WPGraphQL Version

1.19.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL and Headless Login for WPGraphQL

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @jimmysafe - thanks for bringing this up!

 I've had exposing this as a setting on my long-term roadmap, but under the assumption that there was a core WP filter that already handled this. Turns out[I was wrong](https://core.trac.wordpress.org/ticket/37000), so it looks like this needs to be reprioritized.

### that said:

- the plugin uses `wp_authenticate()`, so any drop-in for `wp_set_auth_cookie()` is _probably_ compatible. I haven't tested, but I've seen [this one](https://wordpress.org/plugins/samesite/) referenced a few times.
- how exactly are your frontend and backend URLs configured? Do they match the WP `HOME_URL` and `SITE_URL`?. A lax cookie shouldn't be a problem on a subdomain iirc, but im also pretty sure WordPress takes those values into account when generating.

**Comment by jimmysafe** [comment]
Hey @justlevine thanks for the quick response!

i've just tried the [plugin](https://wordpress.org/plugins/samesite/), but it does not seem to be working for my case ( `define( 'WP_SAMESITE_COOKIE', 'None' );` does not work ).

My frontend and backend urls are configured as follow:

<img width="712" alt="Screenshot 2023-12-21 at 21 01 41" src="https://github.com/AxeWP/wp-graphql-headless-login/assets/12184812/53f2523c-c3ca-4ab1-b825-7d90eac7bd23">

both the Site Address and Wordpress Address urls are the same, they should not be tho, as the frontend will be purely in react and will be hosted under another domain.

Btw if you have any other advice on how i could bypass this SameSite cookie issue it would be amazing!

**Comment by justlevine** [comment]
> both the Site Address and Wordpress Address urls are the same, they should not be tho, as the frontend will be purely in react and will be hosted under another domain.

If you fix the WordPress address, so it's pointing to `http://localhost:5173`, and re-save the permalinks and clear your cookies, do the newly generated cookies work?

**Comment by jimmysafe** [comment]
No, by changing to Wordpress Address to http://localhost:5173 it will actually break the whole wordpress installation as whenever i try to navigate to the wordpress admin dashboard i get this:

<img width="1147" alt="Screenshot 2023-12-22 at 01 04 40" src="https://github.com/AxeWP/wp-graphql-headless-login/assets/12184812/b9f3b900-6fa3-43d0-9c53-63bd4c3673d8">

i have also tried to change the Site Address to http://localhost:5173  but the SameSite cookie issue still persists.

**Comment by jimmysafe** [comment]
@justlevine quick update, googling around i found a solution which finally worked: it's simply by installing [this plugin](https://github.com/MikhailRoot/samesite-cookie-manager).

Btw this should defo be a built in solution for WP-graphql-headless-login as it is such a nice and easy to use plugin!   

I really thank you for the support and the amazing work!

**Comment by justlevine** [comment]
@jimmysafe happy to hear you found a drop-in workaround, and thanks so much for coming back to share!

I'll check it out as soon as I get a free minute - always better IMO to reinforce an existing solution than to reinvent the wheel 🤞

**Comment by alexookah** [comment]
I jumped on the same issue!
It would be awesome if the same functionality would be part of the plugin. Without needing this workaround plugin

**Comment by justlevine** [comment]
Love the idea @alexookah ! Im currently traveling but PRs are always welcome and I just followed up to your discord message, and will take a deeper look at prioritizing this once I'm back at my desk.

**Comment by justlevine** [comment]
Added via #129 courtesy of @alexookah 🙇

Will be included in the upcoming v0.4.0 release.
