### ISSUE TITLE
Documentation Link leads to 404

### ISSUE THREAD

**Issue by M-GRV** [AxeWP/wp-graphql-headless-login#142]
### Description

Just noticed the documentation link on the settings page leads to a 404.

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/97d7fbba-3520-4ce9-8e59-b003db7e8b8e)

### Plugin Version

0.3.1

### WordPress Version

6.6.2

### WPGraphQL Version

1.28.1

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL and Headless Login for WPGraphQL

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Thanks for taking the time to report this @M-GRV !

This is fixed in the admin refactor happening in #141 , which should hopefully be merged and released soon 🤞

**Comment by M-GRV** [comment]
Oh cool an admin refactor! We just started using this for a project and I had noticed that. Thanks for the response!
