### ISSUE TITLE
Document how to bind to `next-auth` / `authjs` ?

### ISSUE THREAD

**Issue by stephane-segning** [AxeWP/wp-graphql-headless-login#58]
### What problem does this address?

I want my WooCommerce users to connect to my application using NextAuth through my Wordpress.

### What is your proposed solution?

I used [Generic OAuth2](https://github.com/AxeWP/wp-graphql-headless-login/blob/develop/docs/mutations.md#login-with-an-oauth2openid-authorization-response) using Auth0. But in development mode it's a nightmare.

### What alternatives have you considered?

I want to use [site token](https://github.com/AxeWP/wp-graphql-headless-login/blob/develop/docs/mutations.md#login-with-a-site-token-and-user-identity) but there's no doc for that

**Comment by justlevine** [comment]
Thanks for this @stephane-segning . I'm in the process of rewriting the example docs, and plan to add examples both for using the `SiteToken` and for using ~NextAuth~ AuthJS, and should have them committed to the repo soon.

**PS:** this issue qualifies for my [WPGraphQL Spring Cleaning](https://axepress.dev/spring) campaign, where I'm donating dev hours to WPGraphQL projects for every issue/PR opened between now and April 31st. If you're interested, let me know via the link where you want the time donated to.

**Comment by justlevine** [comment]
Hey @stephane-segning @imjilk would love your feedback on #63 if you have the time 🙏
(even if its already merged by the time you see this - there's always room for improvement!)
