### ISSUE TITLE
Allow-Access-Control-Credentials header cannot be set. 

### ISSUE THREAD

**Issue by ArkDouglas** [AxeWP/wp-graphql-headless-login#72]
### Description

There's no option to set the Allow-Access-Control-Credentials header in the advanced settings.  The custom fields are appended as a list under another header. 

WPGRAPHQL_CORS has a checkbox for this, but there's a note in this plugin that says it's incompatible

### Steps to reproduce

1. Enable the headless login plugin
2. Attempt to authenticate with a site that requires Allow-Access-Control-Credentials header

### Plugin Version

1.0..0

### WordPress Version

6.2

### WPGraphQL Version

1.14.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL and Headless Login for WPGraphQL

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @ArkDouglas 

A checkbox for toggling `Access-Control-Allow-Credentials` (and auto-setting it if a provider's `Use Authentication Cookie` option is set) is on the to-do-list, although I'm happy to accept PRs if someone wants to beat me to it.

In the interim, you can use the [`graphql_response_headers_to_send` filter](https://www.wpgraphql.com/filters/graphql_response_headers_to_send).

E.g.

```php
add_filter( 'graphql_response_headers_to_send', function ( $headers ): array {
   if ( \WPGraphQL\Login\Utils\Utils::get_access_control_setting( 'shouldBlockUnauthorizedDomains' ) { // or whatever conditional you want to use
    $headers['Access-Control-Allow-Credentials'] = 'true';
  }

  return $headers;
} );
```

**Comment by ArkDouglas** [comment]
That is a valid workaround, thank you.  

I'd love to submit a PR, but I can't for the life of me figure out how you're rendering the dashboard so I can add the checkbox.

**Comment by justlevine** [comment]
> I'd love to submit a PR, but I can't for the life of me figure out how you're rendering the dashboard so I can add the checkbox.

Apologies about that - I should really include some better dev docs.

The [settings config](https://github.com/AxeWP/wp-graphql-headless-login/blob/develop/src/Admin/Settings/AccessControlSettings.php) is sent out as a [JavaScript object](https://github.com/AxeWP/wp-graphql-headless-login/blob/32799aa637a93e9037f3853a7be510a280fd0b7f/src/Admin/Settings.php#L158), and rendered by [Gutenberg](https://github.com/AxeWP/wp-graphql-headless-login/blob/develop/src/assets/js/admin/settings/AccessControlSettings.tsx).

**Comment by ArkDouglas** [comment]
Opened this pull request to address the issue:
https://github.com/AxeWP/wp-graphql-headless-login/pull/74
