### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by mashuxa** [AxeWP/wp-graphql-headless-login#97]
### Description

I caught a fatal error when trying to install the plugin.

### Steps to reproduce

1. Install & activate [WPGraphQL](https://www.wpgraphql.com/).
2. Download the [0.1.4 release](https://github.com/AxeWP/wp-graphql-headless-login/releases/tag/0.1.4) .zip file, upload it to your WordPress install, and try to activate the plugin.

### Plugin could not be activated because it triggered a fatal error.

Warning: require(/var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/autoload_real.php on line 41 Fatal error: Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/../ralouphie/getallheaders/src/getallheaders.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/autoload_real.php:41 Stack trace: #0 /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/autoload_real.php(45): ComposerAutoloaderInite3dd5adcad35e0c0a990ad87f09c52a0::{closure}('7b11c4dc42b3b30...', '/var/www/html/w...') #1 /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/autoload.php(25): ComposerAutoloaderInite3dd5adcad35e0c0a990ad87f09c52a0::getLoader() #2 /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/src/Autoloader.php(33): require_once('/var/www/html/w...') #3 /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/wp-graphql-headless-login.php(34): WPGraphQL\Login\Autoloader::autoload() #4 /var/www/html/wp-admin/includes/plugin.php(2314): include_once('/var/www/html/w...') #5 /var/www/html/wp-admin/plugins.php(192): plugin_sandbox_scrape('wp-graphql-head...') #6 {main} thrown in /var/www/html/wp-content/plugins/wp-graphql-headless-login-0.1.4/vendor/composer/autoload_real.php on line 41

### Plugin Version

0.1.4

### WordPress Version

6.2.2

### WPGraphQL Version

1.19.0

### Additional enviornmental details

docker-compose.yaml:

version: '3.8'
services:
  wordpress:
    image: wordpress:6.2.2
    restart: always
    ports:
      - "8000:80"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: true
      DRAFT_SECRET: ${DRAFT_SECRET}
      DRAFT_COOKIE_LIVE_TIME_S: ${DRAFT_COOKIE_LIVE_TIME_S}
      GRAPHQL_JWT_AUTH_SECRET_KEY: ${GRAPHQL_JWT_AUTH_SECRET_KEY}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
networks:
  my_network:
volumes:
  db_data:

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL and Headless Login for WPGraphQL

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @mashuxa - thanks for reporting this.

What PHP version is your docker running? I'll try and spin up a replication shortly 🤞

**Comment by justlevine** [comment]
Hey @mashuxa would you be able to give #100 a try and see if it fixes your issue?

**Comment by justlevine** [comment]
Hey @mashuxa - never heard back from you.

From the logs you provided, I'm guessing you downloaded the `Source Code` and not the built Release zip (based on the `wp-graphql-headless-login-0.1.4` path, when the release zip doesn't include those suffixed version numbers.

#112 cleaned up some `.gitattributes` properties, but you still should use the release .zip going forward.

I'm going to close this for now, but if you try the [v0.2.0 release .zip](https://github.com/AxeWP/wp-graphql-headless-login/releases/download/0.2.0/wp-graphql-headless-login.zip) and it's still not working, please let me know and I'll reopen this ticket.
